# FlagGame Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/FlagGame

#==================#
#   Basic Config   #
#==================#
# ItemID, used to create/remove Flag blocks
ToolID: 269
# FlagGame World
WorldName: flag
# If it true, Gameworld will be protected by player
WorldProtect: false
# Use debug mode
Debug: false
# Use dynmap layer for show stage information?
UseDynmap: false

#==================#
#   Games Config   #
#==================#
# Countdown time(sec) when starting the game
StartCountdownInSec: 10
# If it true, Play effects when place/break flag
UseFlagEffects: true
# If it true, Kills player when logout during the game
DeathWhenLogout: true
# If it true, Same teams damage will be disabled
DisableTeamPVP: true
# If it true, Prevent regain health on game world
DisableRegainHealth: true
# Lists of disabled commands during the game
DisableCommands:
- /spawn
- /home
- /sethome
- /warp
- /tp
- /pot
- /flymode
- /fm

#==================#
#   MySQL Config   #
#==================#
MySQL:
  Server:
    Address: localhost
    Port: 3306
  Database:
    Name: DatabaseName
    User_Name: UserName
    User_Password: UserPassword
    TablePrefix: flaggame_

#====================#
#   Logging Config   #
#====================#
# DetailLogDirectory
DetailDirectory: plugins/FlagGame/detail/

#========================#
#   Permissions Config   #
#========================#
# Use Permissions List
Permissions:
- vault
- pex
- superperms
- ops

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.2